# Generated by Django 4.2.5 on 2023-09-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trufas', '0002_sabor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sem_Lactose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='sabor',
            name='site',
        ),
    ]
