# Generated by Django 4.2.5 on 2023-09-15 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trufas', '0002_trufa_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='trufa',
            name='sabor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='trufa', to='trufas.sabor'),
            preserve_default=False,
        ),
    ]
