# Generated by Django 4.2.5 on 2023-09-11 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trufas', '0003_sem_lactose_remove_sabor_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combo',
            old_name='descricao',
            new_name='nome',
        ),
    ]
