# Generated by Django 4.2.5 on 2023-09-11 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trufas', '0004_rename_descricao_combo_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combo',
            old_name='nome',
            new_name='descricao',
        ),
    ]
