# Generated by Django 4.2.5 on 2023-09-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trufas', '0004_alter_trufa_combo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trufa',
            name='sem_lactose',
            field=models.ManyToManyField(blank=True, null=True, related_name='trufa', to='trufas.sem_lactose'),
        ),
    ]
