# Generated by Django 4.2.5 on 2023-09-15 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trufas', '0005_alter_trufa_sem_lactose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trufa',
            name='sabor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trufa', to='trufas.sabor'),
        ),
    ]
