# Generated by Django 4.2.5 on 2023-09-11 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trufas', '0005_rename_nome_combo_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trufa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('isbn', models.CharField(blank=True, max_length=32, null=True)),
                ('quantidade', models.IntegerField(blank=True, default=0, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trufa', to='trufas.combo')),
                ('sem_lactose', models.ManyToManyField(related_name='trufa', to='trufas.sem_lactose')),
            ],
        ),
    ]
