# Generated by Django 4.2.5 on 2023-09-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trufas', '0006_trufa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trufa',
            name='isbn',
        ),
    ]
