# Generated by Django 4.2.5 on 2023-09-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trufas', '0007_remove_trufa_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trufa',
            old_name='titulo',
            new_name='nome',
        ),
    ]
