# Generated by Django 4.2.5 on 2023-09-22 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('trufas', '0008_sabor_capa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sem_lactose',
            name='nome',
        ),
        migrations.AddField(
            model_name='sem_lactose',
            name='capa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
        migrations.AddField(
            model_name='sem_lactose',
            name='descricao',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
