# Generated by Django 4.2.5 on 2023-09-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trufas', '0008_rename_titulo_trufa_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trufa',
            old_name='nome',
            new_name='titulo',
        ),
    ]
